services:
  - type: web
    name: pvt-saver-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    plan: free
    envVars:
      - fromDotEnv: true
